/**
 * AI-SDLC: AI as Scribe & Schema Compliance Test Suite
 * Validates that artifacts generated according to the AI as Scribe protocols
 * pass 100% of canonical JSON Schemas without manual syntax intervention.
 */

import * as fs from 'fs';
import * as path from 'path';
import { describe, expect, it } from 'vitest';
import {
  computeCanonicalSha256,
  extractFrontmatter,
  inferArtifactTypeFromId,
  validateArtifactSchema,
  verifyArtifactsSchemas,
} from '../src/index.js';

const repoRoot = path.resolve(__dirname, '../../..');

describe('AI as Scribe & JSON Schema Validation Suite', () => {
  it('should validate that 100% of canonical templates pass JSON schemas', () => {
    const templatesDir = path.join(repoRoot, 'templates');
    const result = verifyArtifactsSchemas({ rootDir: repoRoot, targetPath: templatesDir });

    expect(result.totalEvaluated).toBeGreaterThan(0);
    expect(result.invalidCount).toBe(0);
    expect(result.violations).toHaveLength(0);
    expect(result.success).toBe(true);
  });

  it('should validate that 100% of canonical examples pass JSON schemas', () => {
    const examplesDir = path.join(repoRoot, 'examples');
    const result = verifyArtifactsSchemas({ rootDir: repoRoot, targetPath: examplesDir });

    expect(result.totalEvaluated).toBeGreaterThan(0);
    expect(result.invalidCount).toBe(0);
    expect(result.violations).toHaveLength(0);
    expect(result.success).toBe(true);
  });

  it('should correctly infer artifact type from canonical ID taxonomy', () => {
    expect(inferArtifactTypeFromId('ACT-DRONE-OPERATOR')).toBe('actor');
    expect(inferArtifactTypeFromId('ACT-THREAT-SPOOFER')).toBe('threat-actor');
    expect(inferArtifactTypeFromId('UC-STREAM-TELEMETRY')).toBe('use-case');
    expect(inferArtifactTypeFromId('BR-TELEMETRY-VALIDITY')).toBe('business-rule');
    expect(inferArtifactTypeFromId('FR-TELEMETRY-STREAM-001')).toBe('requirement');
    expect(inferArtifactTypeFromId('QR-LATENCY-REALTIME')).toBe('requirement');
    expect(inferArtifactTypeFromId('CON-LEGACY-COMPATIBILITY')).toBe('requirement');
    expect(inferArtifactTypeFromId('ABUSE-TELEMETRY-SPOOFING')).toBe('abuse-case');
    expect(inferArtifactTypeFromId('SEC-REQ-MTLS-STREAM')).toBe('security-requirement');
    expect(inferArtifactTypeFromId('CMP-TELEMETRY-INGEST')).toBe('component');
    expect(inferArtifactTypeFromId('ADR-001-WEBSOCKET-STACK')).toBe('architecture-decision-record');
    expect(inferArtifactTypeFromId('MAN-USER-SENTINELCORE')).toBe('user-manual');
    expect(inferArtifactTypeFromId('MAN-PROD-SENTINELCORE')).toBe('production-manual');
    expect(inferArtifactTypeFromId('SAF-REQ-ALTITUDE-LIMIT')).toBe('safety-requirement');
    expect(inferArtifactTypeFromId('HAZ-COLLISION-TERRAIN')).toBe('hazard');
    expect(inferArtifactTypeFromId('SEC-ENC-VAULT-PERIMETER')).toBe('security-enclave');
    expect(inferArtifactTypeFromId('JRN-ONBOARDING-OPERATOR')).toBe('journey');
    expect(inferArtifactTypeFromId('TERM-WAYPOINT-ENVELOPE')).toBe('term');
    expect(inferArtifactTypeFromId('CHG-001-TELEMETRY-INGEST')).toBe('spec-change-proposal');
    expect(inferArtifactTypeFromId('DSG-CHG-001-TELEMETRY-INGEST')).toBe('spec-design');
    expect(inferArtifactTypeFromId('SPEC-CHG-001-TELEMETRY-INGEST')).toBe('delivery-spec');
    expect(inferArtifactTypeFromId('MAN-LIC-STATIC-DEPS')).toBe('license-manifest');
    expect(inferArtifactTypeFromId('KPI-REL-V1-0-0')).toBe('release-kpis');
    expect(inferArtifactTypeFromId('TEL-SES-DEV-SESSION')).toBe('session-telemetry');
    expect(inferArtifactTypeFromId('AHOF-DEV-TO-QA')).toBe('agent-handoff');
    expect(inferArtifactTypeFromId('MCP-CFG-WORKSPACE')).toBe('mcp-config');
  });

  it('should validate AI as Scribe generated Product artifacts from natural language prompt', () => {
    // Simulated natural language prompt:
    // "Permitir que los operadores aborten una misión de vuelo si detectan tormentas eléctricas"

    // 1. Actor generated by agent-product-analyst
    const generatedActorYaml = `---
id: ACT-WEATHER-MONITOR
type: actor
title: Sistema de Monitorización Meteorológica en Tiempo Real
status: draft
version: "1.0.0"
schema-version: "1.0"
role-type: external-system
description: Servicio de radar meteorológico que notifica alertas de tormentas en el espacio aéreo.
supersedes: null
superseded-by: null
---
`;
    const actorFm = extractFrontmatter(generatedActorYaml)!;
    expect(actorFm).not.toBeNull();
    const actorValidation = validateArtifactSchema(actorFm, 'actor', repoRoot);
    expect(actorValidation.valid).toBe(true);
    expect(actorValidation.errors).toHaveLength(0);

    // 2. Use case generated by agent-product-analyst
    const generatedUseCaseYaml = `---
id: UC-EMERGENCY-ABORT
type: use-case
title: Aborto de Emergencia de Misión por Alerta Meteorológica
status: draft
version: "1.0.0"
schema-version: "1.0"
primary-actor: ACT-WEATHER-MONITOR
supporting-actors:
  - ACT-DRONE-OPERATOR
governed-by:
  - BR-EMERGENCY-ABORT-AUTHORITY
in-context: BC-AIRSPACE-SAFETY
supersedes: null
superseded-by: null
---
`;
    const ucFm = extractFrontmatter(generatedUseCaseYaml)!;
    expect(ucFm).not.toBeNull();
    const ucValidation = validateArtifactSchema(ucFm, 'use-case', repoRoot);
    expect(ucValidation.valid).toBe(true);
    expect(ucValidation.errors).toHaveLength(0);

    // 3. Functional requirement with Gherkin BDD generated by agent-product-analyst
    const generatedRequirementYaml = `---
id: FR-EMERGENCY-ABORT-001
type: requirement
title: Transmisión y Ejecución de Maniobra de Aborto Inmediato
status: draft
version: "1.0.0"
schema-version: "1.0"
category: functional
derives-from:
  - UC-EMERGENCY-ABORT
verifiable-by: cucumber-bdd
acceptance-format: gherkin
cucumber-tags:
  - "@FR-EMERGENCY-ABORT-001"
  - "@safety"
  - "@automated"
supersedes: null
superseded-by: null
---
`;
    const reqFm = extractFrontmatter(generatedRequirementYaml)!;
    expect(reqFm).not.toBeNull();
    const reqValidation = validateArtifactSchema(reqFm, 'requirement', repoRoot);
    expect(reqValidation.valid).toBe(true);
    expect(reqValidation.errors).toHaveLength(0);

    // 4. Business rule generated by agent-product-analyst
    const generatedRuleYaml = `---
id: BR-EMERGENCY-ABORT-AUTHORITY
type: business-rule
title: Autoridad Exclusiva de Aborto en Situación Crítica
status: draft
version: "1.0.0"
schema-version: "1.0"
enforcement-level: strict-invariant
defined-in: BC-AIRSPACE-SAFETY
supersedes: null
superseded-by: null
---
`;
    const ruleFm = extractFrontmatter(generatedRuleYaml)!;
    expect(ruleFm).not.toBeNull();
    const ruleValidation = validateArtifactSchema(ruleFm, 'business-rule', repoRoot);
    expect(ruleValidation.valid).toBe(true);
    expect(ruleValidation.errors).toHaveLength(0);
  });

  it('should validate AI as Scribe generated Security artifacts from STRIDE inference', () => {
    // Given UC-EMERGENCY-ABORT, agent-threat-modeler infers Denial of Service / Rogue Operator

    // 1. Threat Actor
    const generatedThreatActorYaml = `---
id: ACT-THREAT-ROGUE-OPERATOR
type: threat-actor
title: Operador Malicioso o Credenciales Comprometidas
status: draft
version: "1.0.0"
schema-version: "1.0"
threat-capability: insider-threat
motivation: sabotage
attack-surfaces:
  - "Flight Control WebSocket API"
  - "Emergency Abort Endpoint"
supersedes: null
superseded-by: null
---
`;
    const taFm = extractFrontmatter(generatedThreatActorYaml)!;
    expect(taFm).not.toBeNull();
    const taValidation = validateArtifactSchema(taFm, 'threat-actor', repoRoot);
    expect(taValidation.valid).toBe(true);
    expect(taValidation.errors).toHaveLength(0);

    // 2. Abuse Case
    const generatedAbuseCaseYaml = `---
id: ABUSE-UNAUTHORIZED-MISSION-ABORT
type: abuse-case
title: Inyección Maliciosa de Comando de Aborto Falso
status: draft
version: "1.0.0"
schema-version: "1.0"
primary-threat-actor: ACT-THREAT-ROGUE-OPERATOR
targets-use-case: UC-EMERGENCY-ABORT
stride-category: denial-of-service
mitigated-by:
  - SEC-REQ-ABORT-SIGNATURE
asvs-controls:
  - "OWASP-ASVS-V3.4-Integrity"
supersedes: null
superseded-by: null
---
`;
    const acFm = extractFrontmatter(generatedAbuseCaseYaml)!;
    expect(acFm).not.toBeNull();
    const acValidation = validateArtifactSchema(acFm, 'abuse-case', repoRoot);
    expect(acValidation.valid).toBe(true);
    expect(acValidation.errors).toHaveLength(0);

    // 3. Security Requirement
    const generatedSecReqYaml = `---
id: SEC-REQ-ABORT-SIGNATURE
type: security-requirement
title: Firma Criptográfica Obligatoria en Comandos de Aborto
status: draft
version: "1.0.0"
schema-version: "1.0"
security-domain: cryptography
mitigates-abuse-case:
  - ABUSE-UNAUTHORIZED-MISSION-ABORT
enforced-in-enclave: SEC-ENC-FLIGHT-DISPATCH
compliance-references:
  - "NIST-SP-800-57"
  - "OWASP-ASVS-V3.4"
acceptance-format: gherkin
cucumber-tags:
  - "@SEC-REQ-ABORT-SIGNATURE"
  - "@security"
  - "@mitigation"
supersedes: null
superseded-by: null
---
`;
    const srFm = extractFrontmatter(generatedSecReqYaml)!;
    expect(srFm).not.toBeNull();
    const srValidation = validateArtifactSchema(srFm, 'security-requirement', repoRoot);
    expect(srValidation.valid).toBe(true);
    expect(srValidation.errors).toHaveLength(0);
  });

  it('should compute canonical SHA-256 digests deterministically with LF normalization', () => {
    const rawContentWindows = "line 1\r\nline 2\r\n";
    const rawContentUnix = "line 1\nline 2\n";

    const digestWindows = computeCanonicalSha256(rawContentWindows);
    const digestUnix = computeCanonicalSha256(rawContentUnix);

    expect(digestWindows).toBe(digestUnix);
    expect(digestWindows).toHaveLength(64);
  });

  it('should detect invalid properties or malformed fields deterministically', () => {
    const invalidYaml = `---
id: FR-INVALID-ID
type: requirement
title: AB
status: unknown-status
version: "not-semver"
category: functional
derives-from:
  - UC-VALID-001
verifiable-by: cucumber-bdd
unknown-extra-property: "disallowed"
---
`;
    const fm = extractFrontmatter(invalidYaml)!;
    expect(fm).not.toBeNull();
    const result = validateArtifactSchema(fm, 'requirement', repoRoot);

    expect(result.valid).toBe(false);
    expect(result.errors.length).toBeGreaterThan(0);
    expect(result.errors.some((e) => e.includes('length must be >='))).toBe(true);
    expect(result.errors.some((e) => e.includes('unknown-status'))).toBe(true);
    expect(result.errors.some((e) => e.includes('disallowed extra property'))).toBe(true);
  });

  it('should validate enterprise artifacts: hazard, security-enclave, journey, and term against JSON schemas', () => {
    // 1. Hazard (HAZ)
    const hazardFm = {
      id: 'HAZ-ROTOR-FAILURE-001',
      type: 'hazard',
      title: 'Pérdida de tracción por fallo de rotor primario',
      status: 'active',
      version: '1.0.0',
      severity: 'critical',
      probability: 'remote',
      'fault-tolerance-time-ms': 200,
      'mitigated-by': ['SAF-REQ-ROTOR-REDUNDANCY-001'],
    };
    const hazRes = validateArtifactSchema(hazardFm, 'hazard', repoRoot);
    expect(hazRes.valid).toBe(true);
    expect(hazRes.errors).toHaveLength(0);

    // 2. Security Enclave (SEC-ENC)
    const enclaveFm = {
      id: 'SEC-ENC-HSM-VAULT-001',
      type: 'security-enclave',
      title: 'Enclave Criptográfico de Hardware Seguro',
      status: 'active',
      version: '1.0.0',
      'trust-zone': 'highly-trusted',
      'perimeter-rules': ['mTLS con certificados raíz de hardware', 'Zero inbound sin clave efímera'],
      'allowed-inbound': ['CMP-CRYPTO-SIGNER-001'],
      'allowed-outbound': ['SEC-ENC-AUDIT-LOG-001'],
      'authentication-mechanism': 'mtls',
    };
    const encRes = validateArtifactSchema(enclaveFm, 'security-enclave', repoRoot);
    expect(encRes.valid).toBe(true);
    expect(encRes.errors).toHaveLength(0);

    // 3. Journey (JRN)
    const journeyFm = {
      id: 'JRN-DRONE-MISSION-LIFECYCLE',
      type: 'journey',
      title: 'Ciclo de Vida de Misión de Vuelo Autónomo',
      status: 'active',
      version: '1.0.0',
      persona: 'ACT-DRONE-PILOT-001',
      stages: ['Pre-vuelo', 'Despegue', 'Misión', 'Aterrizaje'],
      touchpoints: ['App Móvil', 'Estación de Telemetría', 'Bocina de Alerta'],
    };
    const jrnRes = validateArtifactSchema(journeyFm, 'journey', repoRoot);
    expect(jrnRes.valid).toBe(true);
    expect(jrnRes.errors).toHaveLength(0);

    // 4. Term (TERM)
    const termFm = {
      id: 'TERM-FTTI-ENVELOPE',
      type: 'term',
      title: 'Fault Tolerant Time Interval (FTTI)',
      status: 'active',
      version: '1.0.0',
      definition: 'Tiempo máximo transcurrido entre la aparición de un fallo y la materialización de un peligro en ausencia de mitigación.',
      'bounded-context': 'FunctionalSafety',
    };
    const termRes = validateArtifactSchema(termFm, 'term', repoRoot);
    expect(termRes.valid).toBe(true);
    expect(termRes.errors).toHaveLength(0);
  });

  it('should validate SDD and telemetry schemas: proposal, design, spec, license-manifest, release-kpis, session-telemetry, agent-handoff, and mcp-config (#55)', () => {
    // 1. spec-change-proposal (proposal.schema.json)
    const validProposal = {
      id: 'CHG-001-AI-TELEMETRY',
      type: 'spec-change-proposal',
      title: 'Ingestión Determinista de Telemetría',
      status: 'draft',
      version: '1.0.0',
      author: 'agent-developer',
      citations: [{ id: 'UC-STREAM-TELEMETRY', digest: 'sha256:0123', comment: 'Base use case' }],
    };
    const propResValid = validateArtifactSchema(validProposal, 'spec-change-proposal', repoRoot);
    expect(propResValid.valid).toBe(true);
    expect(propResValid.errors).toHaveLength(0);

    const invalidProposal = {
      id: 'CHG-001-AI-TELEMETRY',
      type: 'spec-change-proposal',
      status: 'unknown-status',
      disallowedField: true,
    };
    const propResInvalid = validateArtifactSchema(invalidProposal, 'spec-change-proposal', repoRoot);
    expect(propResInvalid.valid).toBe(false);
    expect(propResInvalid.errors.some((e) => e.includes('missing required field'))).toBe(true);

    // 2. spec-design (design.schema.json)
    const validDesign = {
      id: 'DSG-CHG-001-TELEMETRY',
      type: 'spec-design',
      'change-id': 'CHG-001-TELEMETRY',
      title: 'Diseño Técnico de Ingestión',
      version: '1.0.0',
      handoff: 'HOF-CHG-001',
      'architecture-component': 'CMP-TELEMETRY-INGEST',
      enclave: 'SEC-ENC-DMZ',
      status: 'approved',
    };
    const dsgResValid = validateArtifactSchema(validDesign, 'spec-design', repoRoot);
    expect(dsgResValid.valid).toBe(true);
    expect(dsgResValid.errors).toHaveLength(0);

    const invalidDesign = {
      id: 'DSG-CHG-001-TELEMETRY',
      type: 'spec-design',
      title: 'D',
      handoff: 'INVALID-HOF-PATTERN',
    };
    const dsgResInvalid = validateArtifactSchema(invalidDesign, 'spec-design', repoRoot);
    expect(dsgResInvalid.valid).toBe(false);
    expect(dsgResInvalid.errors.some((e) => e.includes('handoff') || e.includes('title'))).toBe(true);

    // 3. delivery-spec (spec.schema.json)
    const validSpec = {
      id: 'SPEC-CHG-001-TELEMETRY',
      type: 'delivery-spec',
      'change-id': 'CHG-001-TELEMETRY',
      profile: 'standard',
      title: 'Especificación de Entrega',
      version: '1.0.0',
      status: 'active',
    };
    const specResValid = validateArtifactSchema(validSpec, 'delivery-spec', repoRoot);
    expect(specResValid.valid).toBe(true);
    expect(specResValid.errors).toHaveLength(0);

    const invalidSpec = {
      id: 'SPEC-CHG-001-TELEMETRY',
      type: 'delivery-spec',
      profile: 'unsupported-profile',
    };
    const specResInvalid = validateArtifactSchema(invalidSpec, 'delivery-spec', repoRoot);
    expect(specResInvalid.valid).toBe(false);
    expect(specResInvalid.errors.some((e) => e.includes('profile'))).toBe(true);

    // 4. license-manifest (license-manifest.schema.json)
    const validManifest = {
      id: 'MAN-LIC-CORE-DEPENDENCIES',
      type: 'license-manifest',
      version: '1.0.0',
      evaluated_dependencies: [
        {
          package: 'picocolors',
          version: '^1.1.0',
          spdx_license: 'ISC',
          status: 'APPROVED',
        },
      ],
    };
    const licResValid = validateArtifactSchema(validManifest, 'license-manifest', repoRoot);
    expect(licResValid.valid).toBe(true);
    expect(licResValid.errors).toHaveLength(0);

    const invalidManifest = {
      id: 'MAN-LIC-CORE-DEPENDENCIES',
      type: 'license-manifest',
      evaluated_dependencies: [
        {
          package: 'bad-pkg',
          version: '1.0.0',
          spdx_license: 'GPL-3.0',
          status: 'DISALLOWED_STATUS',
        },
      ],
    };
    const licResInvalid = validateArtifactSchema(invalidManifest, 'license-manifest', repoRoot);
    expect(licResInvalid.valid).toBe(false);
    expect(licResInvalid.errors.some((e) => e.includes('status'))).toBe(true);

    // 5. release-kpis (release-kpis.schema.json)
    const validReleaseKpis = {
      id: 'KPI-REL-V1-0-0',
      type: 'release-kpis',
      releaseBranch: 'release/v1.0.0',
      baseBranch: 'main',
      generatedAt: '2026-09-24T20:00:00Z',
      totalCommits: 5,
      totalLinesAdded: 500,
      totalLinesDeleted: 50,
      totalKloc: 0.5,
      totalBugs: 1,
      globalDefectDensity: 2.0,
      totalTimeSeconds: 3600,
      totalTokens: 50000,
      totalCostUsd: 0.75,
      authorStats: [
        {
          authorOrModel: 'claude-3-7-sonnet',
          isAgent: true,
          commits: 5,
          linesAdded: 500,
          linesDeleted: 50,
          klocProduced: 0.5,
          bugsInjected: 1,
          defectInjectionRate: 2.0,
          totalTimeSeconds: 3600,
          totalTokens: 50000,
          estimatedCostUsd: 0.75,
        },
      ],
      bugList: [
        {
          sha: 'a1b2c3d',
          subject: 'fix bug',
          author: 'claude-3-7-sonnet',
          timeSeconds: 300,
          tokens: 5000,
        },
      ],
    };
    const kpiResValid = validateArtifactSchema(validReleaseKpis, 'release-kpis', repoRoot);
    expect(kpiResValid.valid).toBe(true);
    expect(kpiResValid.errors).toHaveLength(0);

    const invalidReleaseKpis = {
      id: 'KPI-REL-V1-0-0',
      type: 'release-kpis',
      totalCommits: -5,
    };
    const kpiResInvalid = validateArtifactSchema(invalidReleaseKpis, 'release-kpis', repoRoot);
    expect(kpiResInvalid.valid).toBe(false);
    expect(kpiResInvalid.errors.some((e) => e.includes('missing required field'))).toBe(true);

    // 6. session-telemetry (session-telemetry.schema.json)
    const validSessionTelemetry = {
      id: 'TEL-SES-DEV-001',
      type: 'session-telemetry',
      model: 'gemini-1.5-pro',
      promptTokens: 12000,
      completionTokens: 1500,
      activeTimeSeconds: 180,
      author: 'agent-developer',
      confidence: 'HIGH',
    };
    const sesResValid = validateArtifactSchema(validSessionTelemetry, 'session-telemetry', repoRoot);
    expect(sesResValid.valid).toBe(true);
    expect(sesResValid.errors).toHaveLength(0);

    const invalidSessionTelemetry = {
      id: 'TEL-SES-DEV-001',
      type: 'session-telemetry',
      model: 'gemini-1.5-pro',
      promptTokens: -100,
    };
    const sesResInvalid = validateArtifactSchema(invalidSessionTelemetry, 'session-telemetry', repoRoot);
    expect(sesResInvalid.valid).toBe(false);
    expect(sesResInvalid.errors.some((e) => e.includes('completionTokens') || e.includes('promptTokens'))).toBe(true);

    // 7. agent-handoff (agent-handoff.schema.json)
    const validAgentHandoff = {
      id: 'AHOF-ARCH-TO-QA',
      type: 'agent-handoff',
      'completed-phase': 'Architecture Review',
      'acting-role': 'agent-system-architect',
      'autonomy-mode': 'HUMAN_REVIEW_PLAN',
      deliverables: ['docs/architecture/09_decisions/ADR-001.md'],
      'recommended-next-roles': [
        {
          role: 'agent-qa-engineer',
          rationale: 'Generar casos Gherkin antes de codificar',
        },
      ],
      'suggested-prompt': 'Act as agent-qa-engineer and generate tests',
    };
    const ahofResValid = validateArtifactSchema(validAgentHandoff, 'agent-handoff', repoRoot);
    expect(ahofResValid.valid).toBe(true);
    expect(ahofResValid.errors).toHaveLength(0);

    const invalidAgentHandoff = {
      id: 'AHOF-ARCH-TO-QA',
      type: 'agent-handoff',
      'completed-phase': 'Architecture Review',
      'acting-role': 'unsupported-agent',
      'autonomy-mode': 'HUMAN_REVIEW_PLAN',
      deliverables: [],
    };
    const ahofResInvalid = validateArtifactSchema(invalidAgentHandoff, 'agent-handoff', repoRoot);
    expect(ahofResInvalid.valid).toBe(false);
    expect(ahofResInvalid.errors.some((e) => e.includes('acting-role') || e.includes('deliverables'))).toBe(true);

    // 8. mcp-config (mcp-config.schema.json)
    const validMcpConfig = {
      id: 'MCP-CFG-CURSOR',
      type: 'mcp-config',
      mcpServers: {
        'ai-sdlc': {
          command: 'npx',
          args: ['@ai-sdlc/mcp'],
        },
      },
    };
    const mcpResValid = validateArtifactSchema(validMcpConfig, 'mcp-config', repoRoot);
    expect(mcpResValid.valid).toBe(true);
    expect(mcpResValid.errors).toHaveLength(0);

    const invalidMcpConfig = {
      id: 'MCP-CFG-CURSOR',
      type: 'mcp-config',
      mcpServers: {
        'ai-sdlc': {
          args: ['@ai-sdlc/mcp'],
        },
      },
      disallowedProperty: true,
    };
    const mcpResInvalid = validateArtifactSchema(invalidMcpConfig, 'mcp-config', repoRoot);
    expect(mcpResInvalid.valid).toBe(false);
    expect(mcpResInvalid.errors.some((e) => e.includes('command') || e.includes('disallowedProperty'))).toBe(true);
  });

  it('should verify SEC-REQ-DETERMINISTIC-VERIFY schema compliance and cryptographic hashing', () => {
    const secReqPath = path.join(repoRoot, 'security', 'requirements', 'SEC-REQ-DETERMINISTIC-VERIFY.md');
    expect(fs.existsSync(secReqPath)).toBe(true);
    const content = fs.readFileSync(secReqPath, 'utf-8');
    const { frontmatter } = extractFrontmatter(content);
    expect(frontmatter.id).toBe('SEC-REQ-DETERMINISTIC-VERIFY');
    const res = validateArtifactSchema(frontmatter, 'security-requirement', repoRoot);
    expect(res.valid).toBe(true);
    expect(computeCanonicalSha256(content)).toBeDefined();
  });
});
