/**
 * AI-SDLC: AI as Scribe & Schema Compliance Test Suite
 * Validates that artifacts generated according to the AI as Scribe protocols
 * pass 100% of canonical JSON Schemas without manual syntax intervention.
 */

import * as fs from 'fs';
import * as path from 'path';
import { describe, expect, it } from 'vitest';
import {
  computeCanonicalSha256,
  extractFrontmatter,
  inferArtifactTypeFromId,
  validateArtifactSchema,
  verifyArtifactsSchemas,
} from '../src/index.js';

const repoRoot = path.resolve(__dirname, '../../..');

describe('AI as Scribe & JSON Schema Validation Suite', () => {
  it('should validate that 100% of canonical templates pass JSON schemas', () => {
    const templatesDir = path.join(repoRoot, 'templates');
    const result = verifyArtifactsSchemas({ rootDir: repoRoot, targetPath: templatesDir });

    expect(result.totalEvaluated).toBeGreaterThan(0);
    expect(result.invalidCount).toBe(0);
    expect(result.violations).toHaveLength(0);
    expect(result.success).toBe(true);
  });

  it('should validate that 100% of canonical examples pass JSON schemas', () => {
    const examplesDir = path.join(repoRoot, 'examples');
    const result = verifyArtifactsSchemas({ rootDir: repoRoot, targetPath: examplesDir });

    expect(result.totalEvaluated).toBeGreaterThan(0);
    expect(result.invalidCount).toBe(0);
    expect(result.violations).toHaveLength(0);
    expect(result.success).toBe(true);
  });

  it('should correctly infer artifact type from canonical ID taxonomy', () => {
    expect(inferArtifactTypeFromId('ACT-DRONE-OPERATOR')).toBe('actor');
    expect(inferArtifactTypeFromId('ACT-THREAT-SPOOFER')).toBe('threat-actor');
    expect(inferArtifactTypeFromId('UC-STREAM-TELEMETRY')).toBe('use-case');
    expect(inferArtifactTypeFromId('BR-TELEMETRY-VALIDITY')).toBe('business-rule');
    expect(inferArtifactTypeFromId('FR-TELEMETRY-STREAM-001')).toBe('requirement');
    expect(inferArtifactTypeFromId('QR-LATENCY-REALTIME')).toBe('requirement');
    expect(inferArtifactTypeFromId('CON-LEGACY-COMPATIBILITY')).toBe('requirement');
    expect(inferArtifactTypeFromId('ABUSE-TELEMETRY-SPOOFING')).toBe('abuse-case');
    expect(inferArtifactTypeFromId('SEC-REQ-MTLS-STREAM')).toBe('security-requirement');
    expect(inferArtifactTypeFromId('CMP-TELEMETRY-INGEST')).toBe('component');
    expect(inferArtifactTypeFromId('ADR-001-WEBSOCKET-STACK')).toBe('architecture-decision-record');
    expect(inferArtifactTypeFromId('MAN-USER-SENTINELCORE')).toBe('user-manual');
    expect(inferArtifactTypeFromId('MAN-PROD-SENTINELCORE')).toBe('production-manual');
    expect(inferArtifactTypeFromId('SAF-REQ-ALTITUDE-LIMIT')).toBe('safety-requirement');
  });

  it('should validate AI as Scribe generated Product artifacts from natural language prompt', () => {
    // Simulated natural language prompt:
    // "Permitir que los operadores aborten una misión de vuelo si detectan tormentas eléctricas"

    // 1. Actor generated by agent-product-analyst
    const generatedActorYaml = `---
id: ACT-WEATHER-MONITOR
type: actor
title: Sistema de Monitorización Meteorológica en Tiempo Real
status: draft
version: "1.0.0"
schema-version: "1.0"
role-type: external-system
description: Servicio de radar meteorológico que notifica alertas de tormentas en el espacio aéreo.
supersedes: null
superseded-by: null
---
`;
    const actorFm = extractFrontmatter(generatedActorYaml)!;
    expect(actorFm).not.toBeNull();
    const actorValidation = validateArtifactSchema(actorFm, 'actor', repoRoot);
    expect(actorValidation.valid).toBe(true);
    expect(actorValidation.errors).toHaveLength(0);

    // 2. Use case generated by agent-product-analyst
    const generatedUseCaseYaml = `---
id: UC-EMERGENCY-ABORT
type: use-case
title: Aborto de Emergencia de Misión por Alerta Meteorológica
status: draft
version: "1.0.0"
schema-version: "1.0"
primary-actor: ACT-WEATHER-MONITOR
supporting-actors:
  - ACT-DRONE-OPERATOR
governed-by:
  - BR-EMERGENCY-ABORT-AUTHORITY
in-context: BC-AIRSPACE-SAFETY
supersedes: null
superseded-by: null
---
`;
    const ucFm = extractFrontmatter(generatedUseCaseYaml)!;
    expect(ucFm).not.toBeNull();
    const ucValidation = validateArtifactSchema(ucFm, 'use-case', repoRoot);
    expect(ucValidation.valid).toBe(true);
    expect(ucValidation.errors).toHaveLength(0);

    // 3. Functional requirement with Gherkin BDD generated by agent-product-analyst
    const generatedRequirementYaml = `---
id: FR-EMERGENCY-ABORT-001
type: requirement
title: Transmisión y Ejecución de Maniobra de Aborto Inmediato
status: draft
version: "1.0.0"
schema-version: "1.0"
category: functional
derives-from:
  - UC-EMERGENCY-ABORT
verifiable-by: cucumber-bdd
acceptance-format: gherkin
cucumber-tags:
  - "@FR-EMERGENCY-ABORT-001"
  - "@safety"
  - "@automated"
supersedes: null
superseded-by: null
---
`;
    const reqFm = extractFrontmatter(generatedRequirementYaml)!;
    expect(reqFm).not.toBeNull();
    const reqValidation = validateArtifactSchema(reqFm, 'requirement', repoRoot);
    expect(reqValidation.valid).toBe(true);
    expect(reqValidation.errors).toHaveLength(0);

    // 4. Business rule generated by agent-product-analyst
    const generatedRuleYaml = `---
id: BR-EMERGENCY-ABORT-AUTHORITY
type: business-rule
title: Autoridad Exclusiva de Aborto en Situación Crítica
status: draft
version: "1.0.0"
schema-version: "1.0"
enforcement-level: strict-invariant
defined-in: BC-AIRSPACE-SAFETY
supersedes: null
superseded-by: null
---
`;
    const ruleFm = extractFrontmatter(generatedRuleYaml)!;
    expect(ruleFm).not.toBeNull();
    const ruleValidation = validateArtifactSchema(ruleFm, 'business-rule', repoRoot);
    expect(ruleValidation.valid).toBe(true);
    expect(ruleValidation.errors).toHaveLength(0);
  });

  it('should validate AI as Scribe generated Security artifacts from STRIDE inference', () => {
    // Given UC-EMERGENCY-ABORT, agent-threat-modeler infers Denial of Service / Rogue Operator

    // 1. Threat Actor
    const generatedThreatActorYaml = `---
id: ACT-THREAT-ROGUE-OPERATOR
type: threat-actor
title: Operador Malicioso o Credenciales Comprometidas
status: draft
version: "1.0.0"
schema-version: "1.0"
threat-capability: insider-threat
motivation: sabotage
attack-surfaces:
  - "Flight Control WebSocket API"
  - "Emergency Abort Endpoint"
supersedes: null
superseded-by: null
---
`;
    const taFm = extractFrontmatter(generatedThreatActorYaml)!;
    expect(taFm).not.toBeNull();
    const taValidation = validateArtifactSchema(taFm, 'threat-actor', repoRoot);
    expect(taValidation.valid).toBe(true);
    expect(taValidation.errors).toHaveLength(0);

    // 2. Abuse Case
    const generatedAbuseCaseYaml = `---
id: ABUSE-UNAUTHORIZED-MISSION-ABORT
type: abuse-case
title: Inyección Maliciosa de Comando de Aborto Falso
status: draft
version: "1.0.0"
schema-version: "1.0"
primary-threat-actor: ACT-THREAT-ROGUE-OPERATOR
targets-use-case: UC-EMERGENCY-ABORT
stride-category: denial-of-service
mitigated-by:
  - SEC-REQ-ABORT-SIGNATURE
asvs-controls:
  - "OWASP-ASVS-V3.4-Integrity"
supersedes: null
superseded-by: null
---
`;
    const acFm = extractFrontmatter(generatedAbuseCaseYaml)!;
    expect(acFm).not.toBeNull();
    const acValidation = validateArtifactSchema(acFm, 'abuse-case', repoRoot);
    expect(acValidation.valid).toBe(true);
    expect(acValidation.errors).toHaveLength(0);

    // 3. Security Requirement
    const generatedSecReqYaml = `---
id: SEC-REQ-ABORT-SIGNATURE
type: security-requirement
title: Firma Criptográfica Obligatoria en Comandos de Aborto
status: draft
version: "1.0.0"
schema-version: "1.0"
security-domain: cryptography
mitigates-abuse-case:
  - ABUSE-UNAUTHORIZED-MISSION-ABORT
enforced-in-enclave: SEC-ENC-FLIGHT-DISPATCH
compliance-references:
  - "NIST-SP-800-57"
  - "OWASP-ASVS-V3.4"
acceptance-format: gherkin
cucumber-tags:
  - "@SEC-REQ-ABORT-SIGNATURE"
  - "@security"
  - "@mitigation"
supersedes: null
superseded-by: null
---
`;
    const srFm = extractFrontmatter(generatedSecReqYaml)!;
    expect(srFm).not.toBeNull();
    const srValidation = validateArtifactSchema(srFm, 'security-requirement', repoRoot);
    expect(srValidation.valid).toBe(true);
    expect(srValidation.errors).toHaveLength(0);
  });

  it('should compute canonical SHA-256 digests deterministically with LF normalization', () => {
    const rawContentWindows = "line 1\r\nline 2\r\n";
    const rawContentUnix = "line 1\nline 2\n";

    const digestWindows = computeCanonicalSha256(rawContentWindows);
    const digestUnix = computeCanonicalSha256(rawContentUnix);

    expect(digestWindows).toBe(digestUnix);
    expect(digestWindows).toHaveLength(64);
  });

  it('should detect invalid properties or malformed fields deterministically', () => {
    const invalidYaml = `---
id: FR-INVALID-ID
type: requirement
title: AB
status: unknown-status
version: "not-semver"
category: functional
derives-from:
  - UC-VALID-001
verifiable-by: cucumber-bdd
unknown-extra-property: "disallowed"
---
`;
    const fm = extractFrontmatter(invalidYaml)!;
    expect(fm).not.toBeNull();
    const result = validateArtifactSchema(fm, 'requirement', repoRoot);

    expect(result.valid).toBe(false);
    expect(result.errors.length).toBeGreaterThan(0);
    expect(result.errors.some((e) => e.includes('length must be >='))).toBe(true);
    expect(result.errors.some((e) => e.includes('unknown-status'))).toBe(true);
    expect(result.errors.some((e) => e.includes('disallowed extra property'))).toBe(true);
  });
});
